name: Image-Classifer-Pipeline

on: [push]
jobs:

  pylint_precommit:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12.1"]
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-python-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-python-
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Linting
      run: |
        pylint $(git ls-files '*.py')

      # Build here
    - name: Package creation
      run: |
        python -m pip install --upgrade build
        python -m build
    - name: Archive package
      uses: actions/upload-artifact@v4
      with:
        name: image-classifier
        path: dist
      continue-on-error: false

  acceptance-tests:
    runs-on: ubuntu-latest
    needs: happy-sad-path-tests
    strategy:
      matrix:
        python-version: ["3.12.1"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: image-classifier
        path: dist
    - name: Install whl files
      run: |
        python -m pip install dist/*.whl
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Training Model
      run: |
          python model_creation.py
    - name: Running Acceptance Tests
      run: |  
        coverage run -m pytest -v -s acceptance_test.py

  unit-tests:
    runs-on: ubuntu-latest
    needs: pylint_precommit
    strategy:
      matrix:
        python-version: ["3.12.1"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: image-classifier
        path: dist
    - name: Install whl files
      run: |
        python -m pip install dist/*.whl
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Training Model
      run: |
          python model_creation.py
    - name: Running Unit Tests
      run: |  
        coverage run -m pytest -v -s unit_test.py
      continue-on-error: false
  
  happy-sad-path-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    strategy:
      matrix:
        python-version: ["3.12.1"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: image-classifier
        path: dist
    - name: Install whl files
      run: |
        python -m pip install dist/*.whl
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Training Model
      run: |
          python model_creation.py
    - name: Running Happy & Sad Path Tests
      run: |  
        coverage run -m pytest -v -s happy_sad_test.py
      continue-on-error: false
  
  capacity-test:
    runs-on: ubuntu-latest
    needs: acceptance-tests
    strategy:
      matrix:
        python-version: ["3.12.1"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: image-classifier
        path: dist
    - name: Install whl files
      run: |
        python -m pip install dist/*.whl
    - name: Install Dependencies
      run: |
        pip install -r requirements.txt
    - name: Training Model
      run: |
          python model_creation.py
    - name: Start Flask App
      run: python app.py &
    - name: Run Capacity Test 1u
      run: |
        locust -f test_capacity.py --headless -u 1 -r 5 --host http://localhost:5000 --run-time 2m --html=locustreport1u.html
    - name: Run Capacity Test 5u
      run: |
        locust -f test_capacity.py --headless -u 5 -r 5 --host http://localhost:5000 --run-time 2m --html=locustreport5u.html
    - name: Run Capacity Test 10u
      run: |
        locust -f test_capacity.py --headless -u 10 -r 5 --host http://localhost:5000 --run-time 2m --html=locustreport10u.html
    - name: Upload Capacity Test Report
      uses: actions/upload-artifact@v3
      with:
        name: capacity-test-report
        path: |
          locustreport1u.html
          locustreport5u.html
          locustreport10u.html
